# Generated by Django 4.2.4 on 2023-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_book_authors_alter_book_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
