# Generated by Django 4.2.4 on 2023-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.CharField(max_length=100),
        ),
    ]
